# Generated by Django 4.0.1 on 2022-06-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(default='static/news/images/placeholder-1.jpg', upload_to='images'),
        ),
    ]
