# Generated by Django 4.0.1 on 2022-06-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image',
            field=models.FileField(default='static/news/images/placeholder-1.jpg', upload_to='images'),
        ),
    ]
