# Generated by Django 4.0.1 on 2022-06-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsstory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='pub_date',
            new_name='date',
        ),
    ]
