# Generated by Django 4.0.1 on 2022-06-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_pub_date_newsstory_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='caption',
            field=models.CharField(default='', max_length=250),
        ),
    ]
